version: '3.4'

services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: redmond
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5433:5432"

volumes:
  postgres-db:
    driver: local